django_loginfunction/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'login'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('regist/', include('register.urls')),

]

login/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.loginindex, name="loginindex"),
    path('logincheck', views.logincheck, name="logincheck")
]

register/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "register"

urlpatterns = [
    path('', views.registerindex, name="registerindex"),
    path('idpasswordcheck/', views.idpasswordcheck, name="idpasswordcheck"),
]

login/models.py
from django.db import models

# Create your models here.

register/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    user_id = models.CharField(max_length = 20)
    user_password = models.CharField(max_length = 12)
    user_firstname = models.CharField(max_length = 10)
    user_lastname = models.CharField(max_length = 10)

login/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import auth
from django.http import HttpResponse
from django.contrib import messages

# Create your views here.

def loginindex(request):
    return render(request, 'loginlayout/index.html')


def logincheck(request):
    if request.method == "POST":
        userid = request.POST["id"]
        userpassword = request.POST["password"]
        user = auth.authenticate(request, username = userid, password = userpassword)
        if user is not None:
            auth.login(request, user)
        else:
            messages.info(request, 'Do not match ID or Password')
            return render(request, 'loginlayout/index.html')
    return HttpResponse("Welcome!  " +  request.POST["id"])

register/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib import messages

# Create your views here.
def registerindex(request):
    return render(request, 'registerlayout/index.html')

def idpasswordcheck(request):
    if request.method == "POST":
        try:
            if request.POST["password"] == request.POST["passwordconfig"]:
                user = User.objects.create_user(
                username = request.POST["id"],
                password = request.POST["password"],
                email = request.POST["email"]
                )
            else:
                messages.info(request, 'Do not match password')
                return render(request, 'registerlayout/index.html')

        except Exception as e:
            messages.info(request, 'There is one more ID exist')
            return render(request, 'registerlayout/index.html')
    messages.info(request, 'Finished!')
    return render(request, 'registerlayout/index.html')

login/templates/loginlayout/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Login</title>
</head>

<body>
  {%block contents%}
  <div class="container">
    <center>
      <form action="{%url 'logincheck'%}" , method="POST">
        {% csrf_token %}
        <h3>Login Function (Freez)</h3>
        <br>
        <h3>Id </h3>
        <h5><input type="text" name="id"></h5>
        <h3>Password </h3>
        <h5><input type="password" name="password"></h5>
        <br>
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message.message }}
        </div>
        {% endfor %}

        <h2>
          <input type="submit" class="btn btn-primary" value="Login" id="login">
        </h2>
      </form>
      <input type="submit" value="Register" id="register" onclick="location.href = 'regist'">
    </center>
  </div>
  {%endblock%}
</body>

</html>

register/templates/registerlayout/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Register</title>
</head>

<body>
  {%block contents%}
  <center>
    <div>
      <form action="{%url 'register:idpasswordcheck'%}" method="POST">
        {%csrf_token%}
        {% if messages %}
        <div class="container">
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message.message }}
          </div>
          {% endfor %}
        </div>
        {% endif %}
        <h4>ID </h4>
        <input type="text" name="id" placeholder="Please insert to your ID">
        <br>
        <h4>Password </h4>
        <input type="password" name="password" placeholder="Please insert to your Password">
        <br>
        <h4>Password Configuration </h4>
        <input type="password" name="passwordconfig" placeholder="Please insert one more Password">
        <br>
        <h4>First name </h4>
        <input type="text" name="firstname" placeholder="Please insert to your First name">
        <br>
        <h4>Last name </h4>
        <input type="text" name="lastname" placeholder="Please insert to your Last name">
        <br>
        <h4>E-mail </h4>
        <input type="text" name="email" placeholder="Please insert to your E-mail">
        <br><br><br>
        <input type="submit" class="btn btn-primary" value="Sign in">
      </form>
      <button type="button" name="rewrite">Rewrite</button>
    </div>
  </center>

  {%endblock %}


</body>

</html>